In [108]:
import numpy as np

# Basics

In [109]:
a = np.array([1, 2, 3], dtype="int32")
b = np.array([[5.0, 2.0, 1.0], [7.0, 9.0, 3.0]])
print(a)
print(b)

[1 2 3]
[[5. 2. 1.]
 [7. 9. 3.]]


## Get array dimension

In [110]:
print(a.ndim)
print(b.ndim)

1
2


## Get array shape

In [111]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


## Get array data type

In [112]:
print(a.dtype)
print(b.dtype)

int32
float64


## Get array item size

In [113]:
print(a.itemsize)
print(b.itemsize)

4
8


## Get total size

In [114]:
print(a.size)
print(b.size)
print(a.size * a.itemsize == a.nbytes)

3
6
True


# Accessing elements

In [115]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


## Get a column

In [116]:
c[:, 2]

array([ 3, 10])

# Initializing different types of arrays

## All 0s matrix

In [117]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## All 1s matrix

In [118]:
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

## Any other number

In [119]:
np.full((2, 2), 9)

array([[9, 9],
       [9, 9]])

## Like

In [120]:
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

## Random decimal numbers

In [121]:
np.random.rand(4, 2)

array([[0.24597334, 0.09278829],
       [0.45026388, 0.52495129],
       [0.10774487, 0.74945625],
       [0.13329689, 0.65326876]])

## Random ints

In [122]:
np.random.random_integers(4, 7, size=(3, 3))

array([[5, 4, 7],
       [5, 4, 4],
       [4, 7, 7]])

## Identity matrix

In [123]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Repeat an array

In [124]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Copying arrays

In [125]:
d = np.array([1, 2, 3])
d_copy = np.copy(d)

d_copy[0] = 100

print(d)
print(d_copy)

[1 2 3]
[100   2   3]


# Mathematics

In [126]:
e = np.array([1, 2, 3, 4])

In [127]:
e + 2

array([3, 4, 5, 6])

In [128]:
e - 2

array([-1,  0,  1,  2])

In [129]:
e * 2

array([2, 4, 6, 8])

In [130]:
e / 2

array([0.5, 1. , 1.5, 2. ])

In [131]:
f = np.array([1, 0, 1, 0])

In [132]:
e + f

array([2, 2, 4, 4])

In [133]:
e ** 2

array([ 1,  4,  9, 16])

In [134]:
np.sin(e)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [135]:
g = np.ones((2, 3))
h = np.full((3, 2), 2)

print(g)
print(h)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [136]:
np.matmul(g, h)

array([[6., 6.],
       [6., 6.]])

## Find the determinant

In [137]:
np.linalg.det(np.identity(3))

1.0

# Statistics

In [138]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

In [139]:
np.min(stats)

1

In [140]:
np.max(stats)

6

In [141]:
np.max(stats, axis=1)

array([3, 6])

In [142]:
np.sum(stats)

21

In [143]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing arrays

In [144]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

## Reshaping

In [145]:
print(before.reshape((8, 1)))
print("----------")
print(before.reshape((4, 2)))
print("----------")
print(before.reshape((2, 2, 2)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
----------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Vertical stacking

In [146]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

In [147]:
np.vstack((v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [148]:
np.vstack((v1, v2, v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

## Horizontal stacking

In [149]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [150]:
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

## Boolean masking and advanced indexing

In [151]:
data = np.array([
    [2, 4, 6, 90],
    [5, 8, 1, 3],
    [20, 190, 12, 100],
    [-1, 0, -20, 300]
])

In [152]:
data > 50

array([[False, False, False,  True],
       [False, False, False, False],
       [False,  True, False,  True],
       [False, False, False,  True]])

In [153]:
data[data > 50]

array([ 90, 190, 100, 300])

In [154]:
np.any(data > 50, axis=0)

array([False,  True, False,  True])

In [155]:
np.all(data > 1, axis=1)

array([ True, False,  True, False])

In [156]:
((data > 50) & (data < 300))

array([[False, False, False,  True],
       [False, False, False, False],
       [False,  True, False,  True],
       [False, False, False, False]])

In [157]:
(~((data > 50) & (data < 300)))

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True]])

In [158]:
i = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
i[[1, 2, 8]]

array([2, 3, 9])