In [6]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_absolute_error, mean_squared_error, median_absolute_error, explained_variance_score, r2_score
from sklearn.model_selection import train_test_split

In [2]:
data = np.loadtxt("../../input/data_multivar_regr.txt", delimiter=",")
data[:5]

array([[ 2.06,  3.48,  7.21, 15.69],
       [ 6.37,  3.01,  7.27, 15.34],
       [ 1.18,  1.2 ,  5.42,  0.66],
       [ 7.37,  3.81, -1.95, 38.37],
       [ 6.16,  1.39,  7.39,  9.96]])

In [3]:
X = data[:, :-1]
y = data[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [4]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [5]:
y_pred = model.predict(X_test)
y_pred

array([ 7.84571262e+00,  2.26793589e+01,  2.89460494e+01,  8.96445423e+00,
        1.68076675e+01,  3.70420001e+00,  3.88072610e+01,  4.09890671e+00,
        1.61183560e+01,  3.78549336e+01, -8.43767026e-01,  3.48510437e+01,
        3.03783429e+01,  3.05950167e+01,  1.50335132e+01,  2.44178917e+01,
        9.60327053e+00,  2.21300854e+01,  1.29022870e+01,  1.50599496e-01,
        8.46942650e+00,  1.89068587e+01,  2.88722673e+01,  2.17156914e+01,
        2.94922604e+01,  1.13030848e+01,  2.97992347e+01,  3.30153337e+01,
        4.37419907e+01,  3.43510149e+01,  1.28048047e+01, -2.54899127e+00,
        3.27416549e+01,  1.26700300e+01,  3.10694460e+01,  2.99589429e+01,
        4.03756393e+01,  1.69540356e+01,  2.72078690e+01,  9.25014198e+00,
        2.90583185e+01,  1.00181221e+01,  2.03945692e+01,  3.77007429e+01,
        2.63477347e+01,  2.83374061e+01, -2.30350444e-02,  8.64050027e-02,
        2.91120300e+01,  3.96310430e+01,  4.15883738e+01,  2.68111215e+01,
        2.54927969e+01,  

In [10]:
print("Linear Regressor performance:")
print("Mean absolute error =", round(mean_absolute_error(y_test, y_pred), 2))
print("Mean squared error =", round(mean_squared_error(y_test, y_pred), 2))
print("Median absolute error =", round(median_absolute_error(y_test, y_pred), 2))
print("Explained variance score =", round(explained_variance_score(y_test, y_pred), 2))
print("R2 score =", round(r2_score(y_test, y_pred), 2))

Linear Regressor performance:
Mean absolute error = 3.91
Mean squared error = 23.2
Median absolute error = 3.4
Explained variance score = 0.86
R2 score = 0.86


In [11]:
data[10]

array([ 7.66,  6.29,  5.66, 41.35])

In [12]:
datapoint = [[7.75, 6.35, 5.56]]

In [14]:
polynomial = PolynomialFeatures(degree=10)
X_train_polynomial = polynomial.fit_transform(X_train)
datapoint_polynomial = polynomial.fit_transform(datapoint)

In [15]:
model_polynomial = LinearRegression()
model_polynomial.fit(X_train_polynomial, y_train)

LinearRegression()

In [16]:
print("\nLinear regression:\n", model.predict(datapoint))
print("\nPolynomial regression:\n", model_polynomial.predict(datapoint_polynomial))


Linear regression:
 [35.94599112]

Polynomial regression:
 [42.07608406]
